CREATE USER 'psi'@'localhost' IDENTIFIED BY 'psi';
GRANT ALL PRIVILEGES ON *.* TO 'psi'@'localhost' WITH GRANT OPTION;
CREATE USER 'psi'@'%' IDENTIFIED BY 'psi';
GRANT ALL PRIVILEGES ON *.* TO 'psi'@'%' WITH GRANT OPTION;
CREATE DATABASE psi;